### ISSUE TITLE
When new docker image will be published

### ISSUE THREAD

**Issue by bbrodecki-samsung** [openkruise/kruise-state-metrics#21]
Hi,

I want to know what is the release process and when new docker image will be published?

Best regards

**Comment by furykerry** [comment]
I have pushed the image to dockerhub, and i will update helm chart soon
https://hub.docker.com/layers/openkruise/kruise-state-metrics/v0.2.1/images/sha256-e25af491bc4ad2a87494572649544b588820354738b265ac978087d8705cf684?context=explore
